services:
  - type: web
    name: telegram-mini-shop
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: Telegram Mini Shop
      - key: AUTO_MIGRATE
        value: "true"
      - key: DEBUG
        value: "false"
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: MINI_APP_SHORT_NAME
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: PUBLIC_APP_URL
        sync: false
